version: "3"
services:
  elasticsearch:
    image: elasticsearch:7.5.2
    container_name: elasticsearch
    environment:
      - node.name=elastisearch
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    networks:
      - api

  logstash:
    image: logstash:7.5.2
    container_name: logstash
    volumes:
      - ${PWD}/data:/user/share/logstash/data
    command: >
      sh -c "chmod +x /user/share/logstash/data/initialize_logstash.sh &&
             /user/share/logstash/data/initialize_logstash.sh"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - api
    depends_on:
      - elasticsearch


  api-server:
    image: openjdk:8-jdk-alpine
    container_name: api-server
    volumes:
      - ${PWD}/api-jar:/user/share/api-jar
    command: >
      sh -c "chmod +x /user/share/api-jar/initialize_server.sh &&
             /user/share/api-jar/initialize_server.sh"
    ports:
      - 8080:8080
    networks:
      - api
    depends_on:
      - elasticsearch

networks:
  api:
    driver: bridge